'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Transactions

    '''<summary>
    '''frmTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmTransaction As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''sqldsCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqldsCustomer As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqldsEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqldsEmployee As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqldsItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqldsItem As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlInvoiceLinkStructure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlInvoiceLinkStructure As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqldsInvoiceBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqldsInvoiceBase As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqldsInvoiceSupplementary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqldsInvoiceSupplementary As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''rblInvoiceInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblInvoiceInfo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rblInvoiceDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblInvoiceDetail As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblExistingInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExistingInvoice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExistingInvoiceDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExistingInvoiceDetail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExistingInvoiceInfoInside control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExistingInvoiceInfoInside As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlInvoiceInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInvoiceInfo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblExistingInvoiceDetailInside control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExistingInvoiceDetailInside As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlInvoiceDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInvoiceDetails As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvoiceDetailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceDetailID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomerName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlInvoiceLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInvoiceLink As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCustomerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLinkedInvoiceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLinkedInvoiceID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlInvoiceDetailItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInvoiceDetailItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCustomerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblItemPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItemPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlEmployeeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmployeeID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblItemQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItemQuantity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtItemQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvoiceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblItemPriceTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItemPriceTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvoiceSubtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceSubtotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnInvoiceDetailApply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInvoiceDetailApply As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblInvoiceTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvoiceUpdateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceUpdateDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnInvoiceInfoApply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInvoiceInfoApply As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTransactionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransactionStatus As Global.System.Web.UI.WebControls.Label
End Class
